/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Footer from "../components/Footer"
import Buttonone from "../components/Buttons";
import { useRouter } from "next/router";
import Appbar from "../components/Appbar";

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>iMarket-Wailtlist |Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo1.png" />
      </Head>
   

      <main>
        {/* screen1 */}
        <div className=" container flex-display">
          <div className=" w-100">
            <p className=" face-text">
              Build your Crypto Portfolio with iMarket
            </p>
          </div>
          <div className=" w-100 ps-auto">
            <img
              src="/images/business-3d-355 1.png"
              alt="business"
              className="face-image"
            />
          </div>
        </div>
        {/* screen2 */}

        <div className="white-bg">
          <p className="indexleadtext">What we have to offer</p>
          {/*  */}
          <div className="container-fluid">
            <div className="indflex">
              <div className="index-card">
                <img
                  src="/images/IconP2P.png"
                  alt="IconP2P"
                  className="p2picon"
                />
                <p className="card-titles">Automated P2P</p>
                <p className="card-text">
                  Trade crypto coins without delay from both buyer and seller
                </p>
              </div>
              <div className="index-card">
                <img
                  src="/images/IconTicket.png"
                  alt="IconP2P"
                  className="p2picon"
                />
                <p className="card-titles">E-Ticketing</p>
                <p className="card-text">
                  Buy and Sell your event tickets with fiat or crypto
                </p>
              </div>
              <div className="index-card">
                <img
                  src="/images/IconWallet.png"
                  alt="IconP2P"
                  className="p2picon"
                />
                <p className="card-titles">E-Wallet</p>
                <p className="card-text">
                  Carry out your online transactions without any external
                  interference.
                </p>
              </div>
            </div>
          </div>
          <br/>
          <div className=" pb-5">
        <Buttonone
          onPress={(e) => {
            router.push("about");
          }}
        />
      </div>
          
        </div>
      </main>
     
    </div>
  );
}
